---
title: RSM Engineering Consultants
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: We are an engineering organization operating on national level.  Our
  principal focus is on the practice of structural engineering, wherein we provide
  a rational and responsible approach to engineering problems while seeking a reasonable
  security and compensation for all within the firm. In doing so, we make every possible
  effort to provide a service to our group.
baseurl: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
paginate: 4
paginate_path: blog/page:num
